### ISSUE TITLE
Opção para carregar o API_TOKEN do settings.py do Django

### ISSUE THREAD

**Issue by psnma** [horacioibrahim/iugu-python#5]
Horacio, acho que seria interessante se tivesse a opção de carregar o Token diretamente do settings.py do Django, teria como implementar isso? Poderia haver os seguintes dados no settings do Django:
```
IUGU_TOKEN = ''
IUGU_TOKEN_TEST = ''
IUGU_TEST = True
```
O sistema poderia acessar o settings do Django e capturar o Token direto de lá, exemplo:
```
from django.conf import settings
API_TOKEN = settings.IUGU_TOKEN_TEST if settings.IUGU_TEST else settings.IUGU_TOKEN
```
Nesse caso você poderia tentar carregar o settings.py, caso ocorra erro tentaria carregar o `os.environ["IUGU_API_TOKEN"]` ou vice-versa.

**Comment by psnma** [comment]
Pensando bem, o jeito atual está mais prático e seguro. Esqueça a minha proposta.

**Comment by horacioibrahim** [comment]
Fala @psnma. Interessante tb. Desculpa a demora. Não tinha o hábito, nem recebia alarmes das interações. Obrigado pela sugestão.

**Comment by luanfonceca** [comment]
Fala @psnma e @horacioibrahim eu já prefiro o jeito do settings, caso você ache mais seguro usar variáveis de ambiente, tu pode usar o https://github.com/henriquebastos/django-decouple
